### ISSUE TITLE
Font packages missing for Chinese, Japanese and Korean.

### ISSUE THREAD

**Issue by rsalsbery** [dakboard/Hardware-OS#117]
It was brought to our attention that the latest release was missing fonts for Korean. Upon investigation, I found that it was also missing the Chinese and Japanese fonts as well. We will need to add the following fonts to Chromium to correct this:

- fonts-arphic-ukai 
- fonts-arphic-uming 
- fonts-ipafont-mincho 
- fonts-ipafont-gothic 
- fonts-unfonts-core

For customers who need this now, they can be informed to access the Command Line on their displays via SSH or Direct access and they can use the following command to install these fonts:

`sudo apt-get install fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core`

This will allow Chromium to display these fonts.

**Comment by cocarrig** [comment]
Update included in latest release:
https://github.com/dakboard/Hardware-OS/releases/tag/3.54
