### ISSUE TITLE
Wireless Screen Sharing

### ISSUE THREAD

**Issue by 104e85bd** [dakboard/Hardware-OS#12]
I'm wondering if there's any way currently, or a feature request for the future, for screen sharing to somehow be incorporated into DAKBoard. This way it would turn DAKBoard into a complete conference room solution, akin to something like Airtame. I'd love the ability to be able to cast my screen during meetings from a laptop or mobile device, to present content during meetings/presentations. This is something I would happily pay for, as the current pricing elsewhere is outrageous. In addition, I love the fact that I can use DAKBoard on my own devices.

**Comment by cocarrig** [comment]
Hi 104e85bd,

This will ultimately depend on the device's capabilities that are used to display DAKboard.  The Airplay and other screen sharing protocols being used are intended to be requested and accepted within the same subnet, so DAKboard screen URLs and dakboard.com cannot assist in this design.

At this time we are not investigating a screen sharing mechanism into DAKBoard OS.  Our recommendation to support this design would be to deploy a smart TV that supports screen sharing, and has a build in Web Browser.  The Built in Web Browser can be functional for DAKboard screen URL usage, and the screen sharing can be utilized at any time within the TV's interface.  If the Web browser's functions are not preferred, you can use a Raspberry Pi running DAKboard OS on it to one input, and utilize the screen sharing when needed from the interface.  Reach out to us at contact@dakboard.com and we can point you in the right direction with your hardware.
