### ISSUE TITLE
Touch features not working on OPi 3LTS running v3.53

### ISSUE THREAD

**Issue by jkotecki** [dakboard/Hardware-OS#120]
I am unable to use the touch setup screen to configure the device. After setting it up via wi-fi, the touch features continue to not work. The cursor responds to touch, but I am unable to select the gear or the next screen icons. These features worked perfectly in v103.41.

**Comment by cocarrig** [comment]
Hi @jkotecki,

Can you indicate what kind of touchscreen you are using with this system?

**Comment by cocarrig** [comment]
@jkotecki 

We believe the issue you could have been facing was resolved in the following case, and a fix is now available in version 3.54:
https://github.com/dakboard/Hardware-OS/issues/118

We will be closing this case, if you find alternating information or continues issues please reach out.
