### ISSUE TITLE
IR overlays will not allow you to interact with Screen after reboot

### ISSUE THREAD

**Issue by rsalsbery** [dakboard/Hardware-OS#128]
Related to issue https://github.com/dakboard/Hardware-OS/issues/118. On reboot, the DAKboard OS loses the ability to manipulate the screen with Infrared Overlays, until you unplug and plug the USB back in. 

1. Install and set up OS version 3.54
2. Connect a monitor with an IR overlay for touch
3. After the initial setup is complete reboot the DAKboard CPU
4. The mouse point will be there but you cannot interact with the Display

Expected behavior
On reboot the Screen should remain fully functional

OS versions 3.50 to 3.54

Workaround:
If you unplug the USB for the IR overlay and plug it back in, functionality will be restored.

**Comment by rsalsbery** [comment]
ADDITIONAL Information:

When in portrait mode after reboot, the workaround above will also cause orientation matrix to fail so there is no fix with portrait mode at this time

**Comment by cocarrig** [comment]
Hi @StClairMaverick,

Right now we are focused on a few other bugs and adding the RPi5 support with the addition of the new kernel.  After that we expect to shift focus over to this case and a few others in the backlog.  Apologies but we dont have a timeline yet for this.

**Comment by cocarrig** [comment]
This case has been included as a child case of HArdware-OS #123

**Comment by jatoric** [comment]
Hello,

This issue has been resolved with our latest release v4.03. Which can be downloaded here - https://github.com/dakboard/Hardware-OS/releases/tag/4.03

Thank you!
