### ISSUE TITLE
IR Touch axis inverted after wake from sleep

### ISSUE THREAD

**Issue by scottbryant99** [dakboard/Hardware-OS#129]
**Describe the bug**
I installed DAKboard OS version 3.54 released 11-10-2023 that fixed IR touch inverted on boot. That issue is resolved for me. Sometimes when I touch the DAKboard after it has been operating from for sometime (a day or several days), the touch axis of the IR overlay will be inverted on my portrait DAKboard. It acts like the DAKboard is a landscape oriented DAKboard. To fix this, I reboot the DAKboard and use it until the next recurrence.

I think that this issue is occurring on wake from sleep schedule. 

**To Reproduce**
Walk up to DAKboard and check IR touch orientation after it has woke from sleep. Again this is assumed since the DAKboard boots up in correct IR touch orientation.

This issue is uncommon. Most of the time when I use the DAKboard after it has been operating for more than one day the IR touch orientation is correct. I believe that this issue occurs without my knowledge (I did not touch the DAKboard between a wake schedule) and then fixes itself on the next sleep/wake schedule. This issue can not be commonly recreated.

**Expected behavior**
IR Touch orientation is always correct.

**Screenshots**
None.

**Device Type (please complete the following information):**
- RPi 4b
- Yaegar Woodworks 27 inch portrait DAKboard with IR overlay/
- Raspberry Pi 4B

**DAKboard OS Version (please complete the following information):**
3.54

**Additional context**

**Comment by cocarrig** [comment]
Hi @scottbryant99,

We are finding that the USB connection over time with some devices becomes disasserted and asserted again, registering it as a new device and subsequently failing to interact with the screen as expected.  To fix this we will need to take a more event focused approach to this design, which we have collected requirements into case #123.

If you can subscribe to #123 you will get an update as soon as we can develop a fix.  In the meantime I'll close this case, reopen if necessary.
