### ISSUE TITLE
Touchscreens that register 3 devices in xinput fail to set correctly in chromium

### ISSUE THREAD

**Issue by cocarrig** [dakboard/Hardware-OS#130]
Description:
A DAKboard reseller made us aware of an issue with touch hardware that will register in xinput as 3 different devices.  This appears to cause an issue for the touch input device that is prescribe for chromium, as the touch interactions will not complete in the display URLS.

The following example is the xinput list:
<img width="934" alt="image" src="https://github.com/dakboard/Hardware-OS/assets/76123008/445004c3-3024-4274-a7ba-f60d1f47a42e">

**Comment by jatoric** [comment]
Issue resolved with release 4.04+
