### ISSUE TITLE
Dakboard OS support for Raspberry Pi 5

### ISSUE THREAD

**Issue by cmbehan** [dakboard/Hardware-OS#132]
Just wanted to get some visibility on this issue.

**Comment by cocarrig** [comment]
Hi @cmbehan,

Thanks for the case.  We are tracking this in an internal issue #478 at the moment and this is a work in progress, expected in the next release.

**Comment by cmbehan** [comment]
Fantastic to hear.   Thanks for all the work, this is a wonderful product!

**Comment by cocarrig** [comment]
Completed and released in version 4.01.
https://github.com/dakboard/Hardware-OS/releases/tag/4.01
