### ISSUE TITLE
Add Support for Weida HiTouch Touchscreens

### ISSUE THREAD

**Issue by cocarrig** [dakboard/Hardware-OS#133]
According to client report(Ticket 55500) the following touchscreens will set matrix properly with current system, but will not allow the user to click on the screen, meaning the touch id device ID is identified and /or incorrectly for chromium.  Screen model in question is an asus vt229h:

xinput list output
![image](https://github.com/dakboard/Hardware-OS/assets/76123008/32534b93-42b0-49ee-bebc-de960bb9bfe4)

![image](https://github.com/dakboard/Hardware-OS/assets/76123008/480653ca-4234-400e-9051-fa4d51260dbd)

**Comment by leosouzadias** [comment]
Is there any expectation on when the support will be added?

**Comment by cocarrig** [comment]
Hi @leosouzadias,

Looks like we were unable to test this panel with the release of 4.03 to see if that release fixed this issue.  If I recall correctly this panel assigned the touch device in the opposite manner of what most will do.

If you happen to have this screen, would you mind testing it and let us know your results on the 4.03 release?
https://dakboard.freshdesk.com/support/solutions/articles/35000125880-raspberry-pi-download-and-install-the-dakboard-os

**Comment by cocarrig** [comment]
Closing this issue as resolved for now, and the requester can reopen to provide more details if available.
