### ISSUE TITLE
Hide Scrollbar in browser-init.html

### ISSUE THREAD

**Issue by cocarrig** [dakboard/Hardware-OS#135]
In 4.01 release it is noted that the browser-init.html which is temporarily displayed while checking the network appears with a scrollbar under certain conditions.

**Comment by Dan-Peck** [comment]
I believe changing the `style` of the `BODY` tag to use `margin:0` will help with this.
If that fails, `overflow:hidden` could also work

**Comment by jatoric** [comment]
Tested both `margin: 0` and `overflow: hidden`. Found overflow: hidden to be the better solution for this issue.

**Comment by jatoric** [comment]
Completed and released in 4.02:
https://github.com/dakboard/Hardware-OS/releases/tag/4.02
