### ISSUE TITLE
HotSpot up while connected to ethernet

### ISSUE THREAD

**Issue by jatoric** [dakboard/Hardware-OS#141]
**Describe the bug**
AutoHotSpot is not disabled if the DAKboard CPU is connected to a network via an ethernet cable. 

**To Reproduce**
1. Plug in an ethernet cable for a network connection.
2. Power on DAKboard.
3. Check if AutoHotSpot is available. 

**Expected behavior**
If a network connection be it WiFi or ethernet is detected. AutoHotspot should be disabled. 

**Device Type (please complete the following information):**
- DAKboard CPU 
- DAKboard Wall Display
- Raspberry Pi 

**DAKboard OS Version (please complete the following information):**
4.01

**Comment by cocarrig** [comment]
Fixed in release 4.02
https://github.com/dakboard/Hardware-OS/releases/tag/4.02
