### ISSUE TITLE
Touch Input doesn't Rotate on Acer VT270

### ISSUE THREAD

**Issue by Chris4678** [dakboard/Hardware-OS#158]
**Describe the bug**
The image rotates when set to portrait, however, the touch input does not rotate like it normally does with other screens.

**To Reproduce**
Create dakboard display with Acer VT270 touchscreen
Verify everything works like normal
Set the display to portrait
notice the image rotate but the touch input does not.

**Expected behavior**
The touch input should also rotate with the image

**Screenshots**
This is the xInput list for this monitor connected to a Pi 4 running Dakboard 4.01
![20240424_160003 (1)](https://github.com/dakboard/Hardware-OS/assets/33699866/85436296-6c77-48cd-98fb-b7f8f4101cdb)

**Device Type (please complete the following information):**
- DAKboard CPU (Pi 4 OS 4.01)

**DAKboard OS Version (please complete the following information):**
 4.01

**Additional context**
Running "xinput set-prop 6 "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1" fixes the problem, however the change is overwritten on reboot.

**Comment by jatoric** [comment]
Hello Chris,

This issue should be resolved with the release of our latest OS version 4.03 - 
https://github.com/dakboard/Hardware-OS/releases/tag/4.03.

Thank you!
