### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by arlomiller** [dakboard/Hardware-OS#16]
We recently had an internet outage for a few days. Dakboard display was basically useless

Got me thinking.  This thing is on a Pi and has an SD card.  Why can't there be a local cache of the information, images, calendars, all of it, that would allow the device to continue to work without an active internet connection.  Perhaps not indefinitely, but at least for a few days or a week or something before it HAD to be able to phone home to keep working or something like that...

Frankly, it might be nice for it to not have to always take up bandwidth either.  Perhaps it could poll the cloud for changes, download them to the SD card, and then serve the data from there?

**Comment by cocarrig** [comment]
Please see the following discussion in this project.  We are merging this content with a similar case into a discussion:
https://github.com/dakboard/Hardware-OS/discussions/38
