### ISSUE TITLE
Warning from apt-key: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see te DEPRECATION

### ISSUE THREAD

**Issue by nitr8** [dakboard/Hardware-OS#162]
**Describe the bug**
Running ```sudo apt-get update``` you get the following error:
```W: http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.```

**To Reproduce**
1. SSH to pi
2. Run ```sudo apt-get update```
3. Wait for source list to be updated

**Expected behavior**
No warnings or errors

**Screenshots**

**Device Type**
- Raspberry Pi 4b

**DAKboard OS Version (please complete the following information):**
- DAKboard OS version: 4.02
- Operating System: Raspbian GNU/Linux 12 (bookworm)
- Kernel: Linux 6.1.0-rpi6-rpi-v8

**Additional context**
You can move the existing key to the right place.

```
dakboard:~ $  apt-key list | grep -A4 "trusted.gpg$"
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
/etc/apt/trusted.gpg
--------------------
pub   rsa2048 2012-04-01 [SC]
      A0DA 38D0 D76E 8B5D 6388  7281 9165 938D **90FD DD2E**
uid           [ unknown] Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>
```
Now fix:
```
sudo apt-key export 90FDDD2E | sudo gpg --dearmor -o /tmp/raspi.gpg
sudo apt-key del 90FDDD2E
sudo mv /tmp/raspi.gpg /etc/apt/trusted.gpg.d/
sudo apt-get update 
Hit:1 http://archive.raspberrypi.com/debian bookworm InRelease
Hit:2 http://raspbian.raspberrypi.com/raspbian bookworm InRelease
Reading package lists... Done
```

**Comment by jatoric** [comment]
Fix will be included with DAKboard OS 4.04
