### ISSUE TITLE
Updated Chrome browser is causing an issue with GPU processing on some HTML/Java Script Widgets

### ISSUE THREAD

**Issue by rsalsbery** [dakboard/Hardware-OS#167]
A customer brought to our attention that on version 3.54 the following Widget Code works, while on version 4.03 it fails:

```

<html>
  <style>
    body{
        background-color: #E8F2FF00;
    }
  </style>
  <script src='https://staging-cdn.ndrive.com/nmaps/v1.5.9/nmaps-gl.js'></script>
  <link href='https://staging-cdn.ndrive.com/nmaps/v1.5.9/nmaps-gl.css' rel='stylesheet' />
  <script>

    var coordinates = [
      [[-8.629292,41.158042],12],
      [[-8.6292173274089,41.15795854581039],14],
      [[-8.6292173274089,41.15795854581039],16],
      [[-8.683452,41.183929],14],
      [[-8.621032,41.227890],14],
      [[-8.585845,41.105561],14], 
    ];

    var i = 0;

    update = function() {
      nmapsgl.accessToken = '############';
      nmapsgl.baseApiUrl = 'https://nmaps-dev-gateway.ndrive.com';
      var map = new nmapsgl.Map({
      container: 'map',
      style: 'Light',
      center: [-8.629292,41.158042],
      zoom: 12
      });

      var timer = setInterval(show_location, 10000);

      function show_location(){
        [point, zoom] = coordinates[i];
        map.flyTo({center: point, zoom: zoom});
        i += 1;
        if (i >= coordinates.length){ i = 0; }
      }

    }

  </script>
  <body onload="update()">
    <div id='map' style='width: 1200; height: 1050px;'></div>
  </body>
</html>
```

In testing, we were able to determine that the more updated browser we are using with Bookworm OS is the cause of the failure. Below is an image of the error code we were getting from the OS.

<img width="488" alt="image" src="https://github.com/user-attachments/assets/e1c80814-c95f-4c21-9790-587bc639c880">

The GPU appears to stall while this is running. The Widget opens but nothing renders. This case is being opened to review this and see if there is a solution for this issue with the later OS.

Workaround:

For issues like this the only workaround is to use the legacy OS 3.54.

**Comment by jatoric** [comment]
Issue related to CORS policies from the URL origin, and it's not possible to bypass it due to the security features of Chromium.
