### ISSUE TITLE
DAK Board is no longer loading, or goes to not connecting and blank

### ISSUE THREAD

**Issue by Spartan1498** [dakboard/Hardware-OS#171]
**Describe the bug**
Currently my DAK Board does not load completely for some reason. When I unplug the device, wait, then plug back in, it goes into continual loading or says it cannot load or connect. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Type (please complete the following information):**
- DAKboard CPU [e.g. CPU v4]
- DAKboard Wall Display [e.g Wall Display V2]
- Raspberry Pi [e.g. Raspberry Pi 3B]

**DAKboard OS Version (please complete the following information):**
 If known, please include the DAKboard OS version.

**Additional context**

**Comment by cocarrig** [comment]
Hi @Spartan1498,

This sounds like its probably device specific, and a bad OS or a loose HDMI cable from the Pi to the display.  We would recommend reloading the DAKboard OS firs using the steps below:
https://dakboard.freshdesk.com/support/solutions/articles/35000125880-raspberry-pi-download-and-install-the-dakboard-os

If you're still having trouble, reach out and make a support ticket and we can discuss some problems that may be isolated to your device with you:
https://dakboard.freshdesk.com/support/tickets/new
