### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by TommySharpNZ** [dakboard/Hardware-OS#18]
I'm pretty sure adding Android TV support would make dakboard available to a lot more people.
Instead of my android TV showing me the generic screensaver, showing the Dakboard interface when idle would be super cool!

**Comment by cocarrig** [comment]
Hi Team,

The DAKboard App is also available on android devices as well (which is a website wrapper for our site's functionality).  We have a tutorial for installing and using the App here:
https://dakboard.freshdesk.com/support/solutions/articles/35000190191-dakboard-on-android

You can of course use other tools mentioned previously in this page with your private URL.  You can locate your private URL easily in DAKboard of course:
https://dakboard.freshdesk.com/support/solutions/articles/35000171787-private-urls

For any further ideas for the App, please create a Github Discussion in this project and we would be happy to check them out!
