### ISSUE TITLE
App for Apple TV4k

### ISSUE THREAD

**Issue by DuschdrBabbe** [dakboard/Hardware-OS#19]
A App for Apple TV would  be greate!

Greetings

Pascal

**Comment by cocarrig** [comment]
Hi DuschdrBabbe,

Thank you for taking the time to create this issue.  This has been a feature we would like to have for DAKboard, however the product has taken a different path at this time.  Should there be a change in development into this direction, we will announce it in our [Blog](blog.dakboard.com)
