### ISSUE TITLE
Updating dakboard OS resultat in No content on screen

### ISSUE THREAD

**Issue by hamsjelv** [dakboard/Hardware-OS#2]
Hi dakboard,
After updating raspberry pi (with dakboard os)
The dakboard startstregen was remplacer with a rasbian logo and the dakboard feature is not starting.
Shouldnt it be possible to Update the Raspberry pi ?
If dakboard depends on specifik versions of packages, shouldnt they be held back ?
My alternative is to reinstall dakboard os and only do Security Updates on it, in the future.
What is your opinion on this?

**Comment by cocarrig** [comment]
Hi,

DAKboard's latest release is available on our support website and can be installed onto your SD card to provide the latest OS updates that have been tested by DAKboard:
https://dakboard.freshdesk.com/support/solutions/articles/35000125880-download-and-install-the-dakboard-os-for-raspberry-pi

Any upgrades performed in other manners could be subject to having issues as they have not been tested yet.  Please reach out to support@dakboard.com and we can answer any other questions you may have.
