### ISSUE TITLE
RSS Block Ticker with Slow Scrolling is Choppy

### ISSUE THREAD

**Issue by mjnichols1** [dakboard/Hardware-OS#67]
**Describe the bug**
Using the RSS block as a ticker with slow scrolling is not smooth when displaying on a Pi 4 using DAKboard OS. When using live screen view or preview this issue is not present.

**To Reproduce**
1. Select RSS block
2. Enter RSS feed (example https://www.espn.com/espn/rss/news)
3. Select the following settings:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/91139724/152876614-041a6649-9b9e-4922-8901-f756272cf2d4.png">

**Expected behavior**
The RSS block with these settings as described prior should has a smooth scrolling on the display.

**Comment by cocarrig** [comment]
Hi @Kugelblitz360,

The DAKboard OS 2.32 and higher is running Raspbian Bullseye which uses the new driver, this and acceleration enabled in the browser has provided a bit smoother scrolling performance.  The Pi is still a bit limited in GPU power compared to other device types like workstations, any headway we find to make this better we will incorporate into new releases.  For now we will close this issue unless we have some clear actionable changes to make.

Release information available here:
https://github.com/dakboard/Hardware-OS/releases

**Comment by webash** [comment]
@cocarrig Has there been a regression for hardware acceleration on DAKboard OS for Raspberry Pi? I've got 2 scrolling blocks - a calendar and BBC RSS feed, and both stutter even on 1080p. Checking `htop` reveals CPU usage being hammered.

**Comment by cocarrig** [comment]
Hi @webash,

Scrolling performance has normally improved with each major release incrementally, but some Pis will struggle with it no matter what, especially 512mb Pis like the Zero 2w and the Pi3A boards.  You will get the best results on a Pi4B or a Pi 5 with scrolling at the moment.  If you'd like to share some specifics on your installation feel free to do so and I will see if your experience is expected.

**Comment by cocarrig** [comment]
@webash

Sorry to hear that was not helpful.  We have taken care to dial in the browser options as best as possible per Pi model for things like this.  If your device is operating at 2k or 4k that could contribute to this.  If a Pi 5 is in your budget, you can expect smoother performance from that hardware as another option.

You're welcome to reach out to support and ask for me (Corey) and I can look at your particular screen and device with you to see if there's is anything else I can recommend for your specific instance too:
https://dakboard.freshdesk.com/support/tickets/new

**Comment by webash** [comment]
@cocarrig thanks for the offer - as its just side-gig of mine that I was operating it for (residential building management, how fun), I just chose to remove scrolling in any of the parts of our noticeboard.
