### ISSUE TITLE
Unexpected Reboot

### ISSUE THREAD

**Issue by JuniperMS** [dakboard/Hardware-OS#76]
**Describe the bug**
When rebooting the DAKboard from GUI, if you refresh the page and "/?" is still within the URL, it will reboot the DAKboard over. It will continue to do this until you navigate to the DAKboard by IP address.

**To Reproduce**
1. Go to http://X.X.X.X where X.X.X.X is your DAKboard IP address.
2. Scroll down to "save and reboot"
3. Click on "save and reboot"
4. Notice the URL changes from http://X.X.X.X to http://X.X.X.X/?
5. If you wait for your DAKboard to come back online and then you refresh the page without changing the URL, which is still currently http://X.X.X.X/?, the DAKboard will reboot.

**Expected behavior**
The DAKboard should not reboot when refreshing the page. Instead it should refresh to the DAKboard GUI.

**Screenshots**

**Device Type (please complete the following information):**
- Raspberry Pi Zero 2 W

**DAKboard OS Version (please complete the following information):**
- Linux dakboard 5.15.76-v7+ #1597 | DAKboard OS vers. 3.0

**Additional context**

**Comment by cocarrig** [comment]
Hi @JuniperMS,

This is expected functionality for the design used for creating and submitting the form in the web page.  Your web browser should present the following error, indicating that it will resubmit the form and therefore reboot the device in this case:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/76123008/204820825-96a54054-bb9e-4b16-8b7d-252d10152fb8.png">

I will close this for now.
