### ISSUE TITLE
Dakboard Screen Refresh

### ISSUE THREAD

**Issue by DSO-side** [dakboard/Hardware-OS#8]
I have two Dakboards. Each one is a screen connected to a Raspberry Pi with the Dakboard operating system loaded onto it so they boot directly into the Dakbaord screen.  At times (Sometimes daily or more, sometimes once a week) I will pass the Dakboard and see a completely white screen with a "network couldn't be reached" error. 

I think what must happen is the network connection is lost for a brief amount of time. If I click the raspberry pi off and back on immediately, it will boot right back up to the screen. 

I'm hoping the dakboard software could be set to do that automatically. Ideally, a user could select a frequency, perhaps once an hour, perhaps once a day, to do a complete refresh of the system, so that if the screen info had been lost, it will then be refreshed automatically, without a physical turn of the raspberry pi switch.

Thank you! :)

**Comment by cocarrig** [comment]
Hi,

We are merging this issue into issue #23 .  Please add any additional information you believe is necessary to issue #23.
