### ISSUE TITLE
Auto Setting For Screen Resolution

### ISSUE THREAD

**Issue by cocarrig** [dakboard/Hardware-OS#86]
Description:
Creating this case for the purpose of setting the capability to set the display resolution to Auto in DAKboard OS.  This will function for automatic screen configuration in the /boot/config.txt or xrandr for Pi4B systems:
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/76123008/228598529-25d767fc-c12a-4aa8-bb16-248de8f6b8a7.png">

A new entry named auto in the config page must be created and set as default value.

The default setting for xrandr would be as follows for Pi4B devices in init-display script. Rotation values can be submitted as normal and need no adjustment:
(updated on 9/8/23)
xrandr --output HDMI-1 --rotation normal --auto
xrandr --output HDMI-2 --rotation normal --auto --same-as HDMI-1

For non pi4B systems:
Add no HDMI_mode to the config.txt file, retain rotation settings to result in auto resolution.

display resolution reporting to dakboard.com will need to be redesigned to query xrandr for current setting, as opposed to reporting the configured variable from the config page(auto) which is not helpful for customer support team.

**Comment by DaleJP** [comment]
I do not see any of the ultrawide resolutions on mine even though I is connected to a 21:9 display.

I have the most recent build on a Pi 3b+.  Am I missing something?

**Comment by cocarrig** [comment]
@DaleJP,

Looks like it was uncovered today that one of the support articles indicated that the Pi3B+ can use ultrawide, this is unfortunately not the case and the hardware is not capable of ultrawide.  Only the Pi4B Raspberry Pi computer is capable of running ultrawide HD or ultrawide 2k, sorry for the inconvenience this may have caused you.

**Comment by DaleJP** [comment]
I see. Well that is incredibly disappointing as I've physically mounted an ultrawide monitor at the front of the school for this purpose 😅
Do you have any other suggestions for hardware that will work with an ultrawide? Pi4s are still really hard to come by here.

**Comment by cocarrig** [comment]
@DaleJP,

Sorry, I should have mentioned a few other options for you.  If your device can use ultrawide 2k, then you can use an Orange Pi 3 LTS computer.  It cannot do ultrawide HD as a warning.
This computer is in the [DAKboard CPU v3](https://shop.dakboard.com/collections/dakboard-cpu/products/dakboard-cpu-v3)

You can also download the image if you have an OrangePi 3 LTS just like DAKboard OS from the following support article or purchase the SD card:
https://dakboard.freshdesk.com/support/solutions/articles/35000210494-orange-pi-download-and-install-dakboard-os
https://shop.dakboard.com/products/copy-of-pre-loaded-micro-sd-card-for-orange-pi

**Comment by cocarrig** [comment]
Adding a quick note here that display resolution and orientation reporting to dakboard.com will need to be redesigned to query xrandr for current setting, as opposed to reporting the configured variable from the config page(auto) which is not helpful for customer support team.

**Comment by Dan-Peck** [comment]
Merged in @ d3e89f6 for upcoming release.

**Comment by cocarrig** [comment]
Released in DAKboard-OS 3.52:
https://github.com/dakboard/Hardware-OS/releases/tag/3.52
