### ISSUE TITLE
Add Pi hardware model to device information payload

### ISSUE THREAD

**Issue by cocarrig** [dakboard/Hardware-OS#89]
Description:
To help support client base better, add to the array of reported information from the DAK-OS to dakboard.com the Pi model number.  This will help the support team help clients through specific considerations with different hardware types.

**Comment by Dan-Peck** [comment]
This is included in the work done by Internal-425.  Once released, the DAKOS will send the content of its `/proc/device-tree/model` as `device_model` property.

**Comment by cocarrig** [comment]
PEnding Approval, as release 3.51 is now being transferred to UAT

**Comment by cocarrig** [comment]
UAT Passed, closing.
