### ISSUE TITLE
Clearer warnings needed for site generated password

### ISSUE THREAD

**Issue by cocarrig** [dakboard/Hardware-OS#91]
Description:
Because there is not a physical method to restore a device to factory settings besides imaging the SD card again, this case is being created to warn the client of the impacts of misplacing the password:

Update password warning verbiage to the following
<img width="759" alt="image" src="https://github.com/dakboard/Hardware-OS/assets/76123008/a7a35eca-f87c-4454-a6f3-a1d111b9f5d9">

**Comment by Dan-Peck** [comment]
Merged in @ d16c9b4 for upcoming release.

**Comment by cocarrig** [comment]
3.53 released with update in place:
https://github.com/dakboard/Hardware-OS/releases/tag/3.53
