### ISSUE TITLE
Update the start_time end_time messages reported back to us from Devices

### ISSUE THREAD

**Issue by rsalsbery** [dakboard/Hardware-OS#92]
The wording for the On/Off (Sleep) Schedule in our reported data is a bit confusing and should be updated. See below:

<img width="414" alt="image" src="https://github.com/dakboard/Hardware-OS/assets/107418099/98c6586f-a50f-4962-ac31-fb182585278d">

The start_time should be changed to something like on_time where the end_time should be changed to off_time to make this easier to read when troubleshooting customer devices.

**Comment by Dan-Peck** [comment]
Merged in @ 18d1ec9 for the upcoming release.

**Comment by cocarrig** [comment]
Released in DAKboard-OS 3.52:
https://github.com/dakboard/Hardware-OS/releases/tag/3.52
