### ISSUE TITLE
Browser client (chromium) not updating when 'refresh displays' is pressed

### ISSUE THREAD

**Issue by goodale** [dakboard/Hardware-OS#96]
I'm have a Plus-level Dakboard account (30 day trial).    I've configured a standard Raspberry Pi 4 B and am trying to get DAKBoard to launch in Chromium (kiosk mode) automatically.    I'm using standard Raspberry Pi instead of the DAKBoard image because I want to customize Raspberry pi to use a PIR sensor to enable/disable the monitor automatically to save energy (e.g. turn the monitor on when motion is detected, leave it on for 30 minutes and then turn it off until motion is sensed again)

The motion sensor is working and Chromium is launching directly into the https: link for my board.   However,  the screen isn't updating with changes I've made to layout, even after I press 'Refresh Displays' and wait 10 minutes.

**Comment by cocarrig** [comment]
Hi @goodale 

This can happen sometimes if the wifi signal strength is poor, or there is poor general network connectivity to the device.  The Screen page is listening for instruction to reload, which is sent to it from a specific dakboard cloud appliance.

If may be helpful to understand what browser version this device is on if the above notes are not helpful, and if you continue to have issues we may need some specific details on your account as well.  If that is the case make a ticket at the below portal and we can help you a bit better (just reference this case URL):
https://dakboard.freshdesk.com/support/tickets/new
